import { existsSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
import type { Manifest } from '../persistence/sqlite.js'

/**
 * Writes/refreshes a delimited "DeBob" block in the repo's root `AGENTS.md` so that ANY AI
 * coding agent working in this repo — not just DeBob's own tooling — discovers the persisted
 * graph and prefers querying it over reading raw source files. This is the actual mechanism
 * behind DeBob's core pitch: `debob init`, then any agent knows what to do.
 *
 * Markers make regeneration idempotent: re-running `debob init`/`debob update` replaces only
 * the marked region, never touching the rest of a hand-written AGENTS.md.
 */

const BLOCK_START = '<!-- DEBOB:START — auto-generated by `debob init`/`debob update`, do not edit by hand -->'
const BLOCK_END = '<!-- DEBOB:END -->'

function buildBlock(manifest: Manifest): string {
  const enrichmentNote = manifest.semantic
    ? 'static analysis, Git history, and LLM semantic enrichment (responsibilities, architectural layers)'
    : 'static analysis and Git history (no LLM enrichment yet — run `npx debob update --semantic` for responsibility/layer data)'

  return [
    BLOCK_START,
    '',
    '## DeBob knowledge graph',
    '',
    `This repository has a persistent knowledge graph at \`.debob/context.db\`, built from ${enrichmentNote}.`,
    '',
    '**Before reading source files to answer an architecture, dependency, or responsibility',
    'question about this repo, prefer these commands.** They are grounded in the graph, and',
    'answering from the graph instead of grepping/reading files is the entire point of DeBob:',
    '',
    '```bash',
    '# Answer a free-form question, e.g.:',
    '#   npx debob explain "what does the scanner do?"',
    '#   npx debob explain "what imports the persistence adapter?"',
    '#   npx debob explain "which files are in the data layer?"',
    'npx debob explain "<question>"',
    '',
    '# Explain the impact of the current diff (or against a base ref)',
    'npx debob review [--base <ref>]',
    '```',
    '',
    '**Staleness check** — the graph may lag behind HEAD. Compare the manifest to the current commit:',
    '',
    '```bash',
    "node -e \"console.log(require('./.debob/manifest.json').headCommit)\"",
    'git rev-parse HEAD',
    '```',
    '',
    'If they differ, run `npx debob update` first (add `--semantic` to also refresh LLM enrichments).',
    '',
    'For advanced/raw graph queries the CLI doesn\'t cover, see `.bob/skills/debob-query/SKILL.md`.',
    '',
    '**Never read raw source files to answer a structural question the graph can already answer.**',
    '',
    BLOCK_END,
  ].join('\n')
}

export function writeAgentInstructions(repoRoot: string, manifest: Manifest): void {
  const agentsPath = join(repoRoot, 'AGENTS.md')
  const block = buildBlock(manifest)

  if (!existsSync(agentsPath)) {
    writeFileSync(agentsPath, block + '\n', 'utf-8')
    return
  }

  const existing = readFileSync(agentsPath, 'utf-8')
  const startIdx = existing.indexOf(BLOCK_START)
  const endIdx = existing.indexOf(BLOCK_END)

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    const before = existing.slice(0, startIdx)
    const after = existing.slice(endIdx + BLOCK_END.length)
    writeFileSync(agentsPath, before + block + after, 'utf-8')
  } else {
    const separator = existing.endsWith('\n\n') ? '' : existing.endsWith('\n') ? '\n' : '\n\n'
    writeFileSync(agentsPath, existing + separator + block + '\n', 'utf-8')
  }
}
